dist: trusty
language: cpp

sudo: required
addons:
  apt:
    sources:
      - sourceline: ppa:team-gcc-arm-embedded/ppa
    packages:
      - gcc-arm-embedded

script:
  - make 

#deploy:
#  skip_cleanup: true
#  file_glob: true
#  file: build/*.elf
#  api_key: ${GITHUB_KEY}
#  provider: releases
#  overwrite: true
#  on:
#    tags: true
#notifications:
#  email: false
