dist: trusty
language: cpp
addons:
  addons:
    apt:
        packages:
        - libnewlib-arm-none-eabi
        - gcc-arm-none-eabi
        - build-essential
script:
  - make 

#deploy:
#  skip_cleanup: true
#  file_glob: true
#  file: build/*.elf
#  api_key: ${GITHUB_KEY}
#  provider: releases
#  overwrite: true
#  on:
#    tags: true
#notifications:
#  email: false
